// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udruawrcioawwcoifybo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkcnVhd3JjaW9hd3djb2lmeWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzMzMjAsImV4cCI6MjA2NDMwOTMyMH0.f_au1434532-zuUyAKTbZ-5mpea7jL893kknXPvZkbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);